### PR TITLE
Add wallet transer method

### PR DESCRIPTION
**Pull request by abrahamchaibi**

### CODE REVIEW

**Comment by abrahamchaibi** [comment]
@CliffS possible to add in support for the walletTransfer method? Documented [here](https://www.kraken.com/features/api) under section "Wallet Transfer"

**Review by ghost — APPROVED** [review]
README need updating.

**Comment by CliffS** [comment]
@abrahamchaibi Thank you for the update.

**Comment by abrahamchaibi** [comment]
Thank you!!!

**Pull request merged**
